import { CraftResponse } from "@/types/CraftResponse";

export const CraftResponseA: CraftResponse = {
  added: [
    {
      deltaCount: 1,
      playerLoot: {
        asset: "",
        count: 1,
        disenchantLootName: "CURRENCY_champion",
        disenchantValue: 960,
        displayCategories: "CHAMPION",
        expiryTime: -1,
        isNew: true,
        isRental: true,
        itemDesc: "Lulu",
        itemStatus: "OWNED",
        localizedDescription: "",
        localizedName: "",
        localizedRecipeSubtitle: "",
        localizedRecipeTitle: "",
        lootId: "CHAMPION_RENTAL_117",
        lootName: "CHAMPION_RENTAL_117",
        parentItemStatus: "NONE",
        parentStoreItemId: -1,
        rarity: "DEFAULT",
        redeemableStatus: "ALREADY_OWNED",
        refId: "",
        rentalGames: 0,
        rentalSeconds: 604800,
        shadowPath: "",
        splashPath: "/lol-game-data/assets/v1/champion-splashes/117/117000.jpg",
        storeItemId: 117,
        tags: "",
        tilePath: "/lol-game-data/assets/v1/champion-tiles/117/117000.jpg",
        type: "CHAMPION_RENTAL",
        upgradeEssenceName: "CURRENCY_champion",
        upgradeEssenceValue: 2880,
        upgradeLootName: "CHAMPION_117",
        value: 4800,
      },
    },
  ],
  redeemed: [],
  removed: [
    {
      deltaCount: 1,
      playerLoot: {
        asset: "",
        count: 123,
        disenchantLootName: "",
        disenchantValue: 0,
        displayCategories: "CHEST",
        expiryTime: -1,
        isNew: false,
        isRental: false,
        itemDesc: "",
        itemStatus: "NONE",
        localizedDescription: "",
        localizedName: "",
        localizedRecipeSubtitle: "",
        localizedRecipeTitle: "",
        lootId: "CHEST_128",
        lootName: "CHEST_128",
        parentItemStatus: "NONE",
        parentStoreItemId: -1,
        rarity: "DEFAULT",
        redeemableStatus: "NOT_REDEEMABLE",
        refId: "",
        rentalGames: 0,
        rentalSeconds: 0,
        shadowPath: "",
        splashPath: "/fe/lol-loot/assets/loot_item_icons/chest_128.png",
        storeItemId: 128,
        tags: "",
        tilePath: "/fe/lol-loot/assets/loot_item_icons/chest_128.png",
        type: "CHEST",
        upgradeEssenceName: "",
        upgradeEssenceValue: 0,
        upgradeLootName: "",
        value: 0,
      },
    },
  ],
};

export const CraftResponseB: CraftResponse = {
  added: [
    {
      deltaCount: 1,
      playerLoot: {
        asset: "",
        count: 4,
        disenchantLootName: "CURRENCY_champion",
        disenchantValue: 90,
        displayCategories: "CHAMPION",
        expiryTime: -1,
        isNew: true,
        isRental: true,
        itemDesc: "Soraka",
        itemStatus: "OWNED",
        localizedDescription: "",
        localizedName: "",
        localizedRecipeSubtitle: "",
        localizedRecipeTitle: "",
        lootId: "CHAMPION_RENTAL_16",
        lootName: "CHAMPION_RENTAL_16",
        parentItemStatus: "NONE",
        parentStoreItemId: -1,
        rarity: "DEFAULT",
        redeemableStatus: "ALREADY_OWNED",
        refId: "",
        rentalGames: 0,
        rentalSeconds: 604800,
        shadowPath: "",
        splashPath: "/lol-game-data/assets/v1/champion-splashes/16/16000.jpg",
        storeItemId: 16,
        tags: "",
        tilePath: "/lol-game-data/assets/v1/champion-tiles/16/16000.jpg",
        type: "CHAMPION_RENTAL",
        upgradeEssenceName: "CURRENCY_champion",
        upgradeEssenceValue: 270,
        upgradeLootName: "CHAMPION_16",
        value: 450,
      },
    },
    {
      deltaCount: 1,
      playerLoot: {
        asset: "",
        count: 4,
        disenchantLootName: "CURRENCY_champion",
        disenchantValue: 630,
        displayCategories: "CHAMPION",
        expiryTime: -1,
        isNew: true,
        isRental: true,
        itemDesc: "Vladimir",
        itemStatus: "OWNED",
        localizedDescription: "",
        localizedName: "",
        localizedRecipeSubtitle: "",
        localizedRecipeTitle: "",
        lootId: "CHAMPION_RENTAL_8",
        lootName: "CHAMPION_RENTAL_8",
        parentItemStatus: "NONE",
        parentStoreItemId: -1,
        rarity: "DEFAULT",
        redeemableStatus: "ALREADY_OWNED",
        refId: "",
        rentalGames: 0,
        rentalSeconds: 604800,
        shadowPath: "",
        splashPath: "/lol-game-data/assets/v1/champion-splashes/8/8000.jpg",
        storeItemId: 8,
        tags: "",
        tilePath: "/lol-game-data/assets/v1/champion-tiles/8/8000.jpg",
        type: "CHAMPION_RENTAL",
        upgradeEssenceName: "CURRENCY_champion",
        upgradeEssenceValue: 1890,
        upgradeLootName: "CHAMPION_8",
        value: 3150,
      },
    },
    {
      deltaCount: 1,
      playerLoot: {
        asset: "",
        count: 4,
        disenchantLootName: "CURRENCY_champion",
        disenchantValue: 90,
        displayCategories: "CHAMPION",
        expiryTime: -1,
        isNew: true,
        isRental: true,
        itemDesc: "Garen",
        itemStatus: "OWNED",
        localizedDescription: "",
        localizedName: "",
        localizedRecipeSubtitle: "",
        localizedRecipeTitle: "",
        lootId: "CHAMPION_RENTAL_86",
        lootName: "CHAMPION_RENTAL_86",
        parentItemStatus: "NONE",
        parentStoreItemId: -1,
        rarity: "DEFAULT",
        redeemableStatus: "ALREADY_OWNED",
        refId: "",
        rentalGames: 0,
        rentalSeconds: 604800,
        shadowPath: "",
        splashPath: "/lol-game-data/assets/v1/champion-splashes/86/86000.jpg",
        storeItemId: 86,
        tags: "",
        tilePath: "/lol-game-data/assets/v1/champion-tiles/86/86000.jpg",
        type: "CHAMPION_RENTAL",
        upgradeEssenceName: "CURRENCY_champion",
        upgradeEssenceValue: 270,
        upgradeLootName: "CHAMPION_86",
        value: 450,
      },
    },
    {
      deltaCount: 1,
      playerLoot: {
        asset: "",
        count: 1,
        disenchantLootName: "CURRENCY_champion",
        disenchantValue: 630,
        displayCategories: "CHAMPION",
        expiryTime: -1,
        isNew: true,
        isRental: true,
        itemDesc: "Karthus",
        itemStatus: "OWNED",
        localizedDescription: "",
        localizedName: "",
        localizedRecipeSubtitle: "",
        localizedRecipeTitle: "",
        lootId: "CHAMPION_RENTAL_30",
        lootName: "CHAMPION_RENTAL_30",
        parentItemStatus: "NONE",
        parentStoreItemId: -1,
        rarity: "DEFAULT",
        redeemableStatus: "ALREADY_OWNED",
        refId: "",
        rentalGames: 0,
        rentalSeconds: 604800,
        shadowPath: "",
        splashPath: "/lol-game-data/assets/v1/champion-splashes/30/30000.jpg",
        storeItemId: 30,
        tags: "",
        tilePath: "/lol-game-data/assets/v1/champion-tiles/30/30000.jpg",
        type: "CHAMPION_RENTAL",
        upgradeEssenceName: "CURRENCY_champion",
        upgradeEssenceValue: 1890,
        upgradeLootName: "CHAMPION_30",
        value: 3150,
      },
    },
    {
      deltaCount: 180,
      playerLoot: {
        asset: "currency_champion",
        count: 10478,
        disenchantLootName: "",
        disenchantValue: 0,
        displayCategories: "",
        expiryTime: -1,
        isNew: true,
        isRental: false,
        itemDesc: "",
        itemStatus: "NONE",
        localizedDescription: "",
        localizedName: "",
        localizedRecipeSubtitle: "",
        localizedRecipeTitle: "",
        lootId: "CURRENCY_champion",
        lootName: "CURRENCY_champion",
        parentItemStatus: "NONE",
        parentStoreItemId: -1,
        rarity: "DEFAULT",
        redeemableStatus: "NOT_REDEEMABLE",
        refId: "",
        rentalGames: -1,
        rentalSeconds: -1,
        shadowPath: "",
        splashPath: "/fe/lol-loot/assets/loot_item_icons/currency_champion.png",
        storeItemId: 6,
        tags: "",
        tilePath: "/fe/lol-loot/assets/loot_item_icons/currency_champion.png",
        type: "CURRENCY",
        upgradeEssenceName: "CURRENCY_champion",
        upgradeEssenceValue: 10,
        upgradeLootName: "",
        value: 1,
      },
    },
  ],
  redeemed: [],
  removed: [
    {
      deltaCount: 2,
      playerLoot: {
        asset: "",
        count: 121,
        disenchantLootName: "",
        disenchantValue: 0,
        displayCategories: "CHEST",
        expiryTime: -1,
        isNew: false,
        isRental: false,
        itemDesc: "",
        itemStatus: "NONE",
        localizedDescription: "",
        localizedName: "",
        localizedRecipeSubtitle: "",
        localizedRecipeTitle: "",
        lootId: "CHEST_128",
        lootName: "CHEST_128",
        parentItemStatus: "NONE",
        parentStoreItemId: -1,
        rarity: "DEFAULT",
        redeemableStatus: "NOT_REDEEMABLE",
        refId: "",
        rentalGames: 0,
        rentalSeconds: 0,
        shadowPath: "",
        splashPath: "/fe/lol-loot/assets/loot_item_icons/chest_128.png",
        storeItemId: 128,
        tags: "",
        tilePath: "/fe/lol-loot/assets/loot_item_icons/chest_128.png",
        type: "CHEST",
        upgradeEssenceName: "",
        upgradeEssenceValue: 0,
        upgradeLootName: "",
        value: 0,
      },
    },
  ],
};
